version: '3'

services:
  flask-app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - app-network
    volumes:
      - ./data:/app/data

  webserver:
    image: nginx:alpine
    volumes:
      - ./html:/usr/share/nginx/html
     # - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
